package com.example.sp2.data.local.entity

import androidx.room.Entity
import androidx.room.PrimaryKey

// Represents a note stored in the local database
@Entity(tableName = "notes")
data class NoteEntity(

    // Unique ID generated by Room
    @PrimaryKey(autoGenerate = true)
    val id: Int = 0,

    val title: String,
    val content: String,
    val date: String
)