package com.example.sp2.data.local.entity

import androidx.room.Entity
import androidx.room.PrimaryKey

// Represents a task stored in the local database
@Entity(tableName = "tasks")
data class TaskEntity(

    // Unique ID generated by Room
    @PrimaryKey(autoGenerate = true)
    val id: Int = 0,

    val title: String,
    val description: String = "",

    // Dates and times are stored as text
    val date: String? = null,
    val time: String? = null,

    // Enums are stored as text
    val priority: String,
    val completed: Boolean = false,
    val reminder: String,
    val repeat: String
)